file = open("file.txt", 'w')
L = ["This Logos\n", "This is python\n", "This is FCC\n"]
file.write("Hello there\n")
file.writelines(L)
file.close()
file = open("file.txt", "rt")
print("Output of the read function is")
print(file.read())
print()
file.seek(0)
print("The output of readline function is")
print(file.readline())
print()
file.seek(0)
print("Output of readlines function is")
print(file.readlines())
print()
file.close()
