CREATE TABLE supplier (
	supp_id INT(2),
	supp_name VARCHAR2,
	product VARCHAR2,
)

CREATE SEQUENCE supp
	START WITH 1
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 50
	NOCYCLE
	NOCACHE;

ALTER SEQUENCE supp INCREMENT BY 1;